---
# Base role handlers.

- name: Restart redis-server
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
